name: Java CI with Maven

on:  # это когда будет запускаться jobs
  push:
    branches: [ "develop", "feature/*" , "main" ]
  pull_request:
    branches: [ "main" ]

jobs:  # что делаем когде сработает условие из on
  build: # имя job(можно написать любое) CI job — сборка и тесты
    runs-on: ubuntu-latest   # Виртуальная машина, на которой будет выполняться шаги

    steps:                   # Последовательность шагов в одном job
      - name: Checkout code   #скачивает код
        uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build jar and test
        run: ./mvnw clean install

      - name: Archive JAR for deploy job # сохранили в github actions чтобы можно было его скачать или передать в другие workflows
        uses: actions/upload-artifact@v4
        with:
          name: eduka-jar
          path: target/eduka-0.0.1-SNAPSHOT.jar