name: Deploy on main push

on:
  workflow_run:
    workflows: ["Java CI/CD with Maven and Docker"]
    types:
      - completed

jobs:
  deploy:  # CD job — пуш Docker и деплой
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact from build workflow
        uses: actions/download-artifact@v4
        with:
          name: eduka-jar
          path: ./target

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t evgenn4ke/eduka:latest .
          docker push evgenn4ke/eduka:latest

      # Раскомментируй и настрой, если хочешь деплой на VPS
      # - name: Deploy to VPS via SSH
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.SERVER_IP }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       docker pull evgenn4ke/eduka:latest
      #       docker stop eduka || true
      #       docker rm eduka || true
      #       docker run -d --name eduka -p 8080:8080 evgenn4ke/eduka:latest